# Generated by Django 2.1.7 on 2019-03-31 02:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocktail_name', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2019, 3, 31, 2, 36, 1, 807733, tzinfo=utc))),
                ('cocktail_type', models.CharField(choices=[('WHISKEY', 'Whiskey'), ('VODKA', 'Vodka'), ('TEQUILA', 'Tequila'), ('GIN', 'Gin'), ('VIRGIN', 'Virgin')], max_length=10)),
            ],
        ),
    ]
