# Generated by Django 2.1.7 on 2019-03-31 02:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('barback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 31, 2, 36, 23, 761313, tzinfo=utc)),
        ),
    ]
