# Generated by Django 2.1.7 on 2019-03-27 23:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('barback', '0002_remove_cocktail_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 23, 46, 44, 369645, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='cocktail_type',
            field=models.CharField(choices=[('WHISKEY', 'Whiskey'), ('VODKA', 'Vodka'), ('TEQUILA', 'Tequila'), ('GIN', 'Gin'), ('VIRGIN', 'Virgin')], max_length=10),
        ),
    ]
