# Generated by Django 2.1.7 on 2019-03-31 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barback', '0002_auto_20190330_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='cocktail_image',
            field=models.ImageField(default='cocktail', upload_to=''),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
