# Generated by Django 2.1.7 on 2019-03-29 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barback', '0003_auto_20190327_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='pub_date',
        ),
    ]
