# Generated by Django 2.1.7 on 2019-03-31 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barback', '0003_auto_20190330_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
