# Generated by Django 2.1.7 on 2019-03-29 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barback', '0004_remove_cocktail_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='creator',
            field=models.ForeignKey(default='The House', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
