# Generated by Django 2.1.7 on 2019-03-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barback', '0004_auto_20190330_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='cocktail_image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
