# Generated by Django 2.1.7 on 2019-04-02 00:19

import barback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barback', '0005_auto_20190330_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='cocktail_image',
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
    ]
