# Generated by Django 2.1.7 on 2019-03-29 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barback', '0006_auto_20190328_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
