# Generated by Django 2.1.7 on 2019-03-29 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barback', '0007_auto_20190328_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='creator',
        ),
    ]
