# Generated by Django 2.1.7 on 2019-04-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barback', '0008_auto_20190402_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='cocktail_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
