# Generated by Django 2.1.7 on 2019-03-29 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barback', '0009_cocktail_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
