# Generated by Django 2.1.7 on 2019-04-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barback', '0009_cocktail_cocktail_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='cocktail_steps',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
