# Generated by Django 2.1.7 on 2019-04-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barback', '0010_cocktail_cocktail_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='virgin',
            field=models.BooleanField(null=True),
        ),
    ]
