# Generated by Django 2.1.7 on 2019-04-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barback', '0011_cocktail_virgin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='cocktail_image',
            field=models.ImageField(null=True, upload_to='cocktail_images/'),
        ),
    ]
