# Generated by Django 2.1.7 on 2019-04-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barback', '0012_auto_20190409_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='cocktail_image',
            field=models.ImageField(blank=True, null=True, upload_to='cocktail_images/'),
        ),
    ]
