# Generated by Django 2.1.7 on 2019-04-23 01:01

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('barback', '0018_auto_20190414_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('cocktail_image', '270x180', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='cocktail_image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='cocktail_images/'),
        ),
    ]
