# Generated by Django 2.1.7 on 2019-04-23 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barback', '0019_auto_20190422_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='cocktail_images/')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
            },
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='cropping',
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='cocktail_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barback.Photo'),
        ),
    ]
