# Generated by Django 2.1.7 on 2019-04-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barback', '0020_auto_20190422_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='cocktail_image',
            field=models.ImageField(blank=True, null=True, upload_to='cocktail_images/'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
