# Generated by Django 2.1.7 on 2019-04-23 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barback', '0022_cocktail_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocktail',
            old_name='public',
            new_name='private',
        ),
    ]
