# Generated by Django 2.1.7 on 2019-05-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barback', '0023_auto_20190423_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocktail',
            old_name='private',
            new_name='public',
        ),
        migrations.AddField(
            model_name='cocktail',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
