# Generated by Django 2.1.7 on 2019-05-07 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barback', '0024_auto_20190505_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
