# Generated by Django 2.1.7 on 2019-05-07 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barback', '0025_auto_20190506_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barback.UserProfile'),
        ),
    ]
